### ISSUE TITLE
AlphaAction code is not updated

### ISSUE THREAD

**Issue by netanellavisdris** [MCG-NJU/STMixer#1]
Hi,
When trying to run the repository,
I've got this error :
```bash
Traceback (most recent call last):
  File "train_net.py", line 12, in <module>
    from alphaction.dataset import make_data_loader
  File "/home/netanell/work/STMixer/alphaction/dataset/__init__.py", line 1, in <module>
    from .build import make_data_loader
  File "/home/netanell/work/STMixer/alphaction/dataset/build.py", line 5, in <module>
    from . import datasets as D
  File "/home/netanell/work/STMixer/alphaction/dataset/datasets/__init__.py", line 3, in <module>
    from .ava_kinetics import AvaKinetics
ModuleNotFoundError: No module named 'alphaction.dataset.datasets.ava_kinetics'
```
It seems that there is mismatch in alphaction code used here.

Best,
   Netanell

**Comment by atao99** [comment]
Thanks for pointing out this issue.  We've fixed it.

**Comment by netanellavisdris** [comment]
Thanks for the quick fix.

Results are close to the reported one with pretrained weights
We got 0.3489 mAP@IOU=0.5 on AVA eval with VMAE-Vit-BV2
While in the paper you report 36.1 mAP. 
Does the published weights are the one you got AVA v2.2 results?

Thanks,
   Netanell.

**Comment by atao99** [comment]
We did the evaluation again and we found no problems here. Could you confirm whether it is only the model with VMAEv2-ViT-B backbone that has the problem or other models also have the problem?
<img width="586" alt="Snipaste_2023-05-18_15-38-54" src="https://github.com/MCG-NJU/STMixer/assets/38271412/5f1e3792-528f-4785-b485-48c05569ed92">

**Comment by netanellavisdris** [comment]
We only check VMAEv2-ViT-B backbone and got these results
```
2023-05-11 19:37:36,494 alphaction.inference INFO: { 'PascalBoxes_PerformanceByCategory/AP@0.5IOU/answer phone': 0.819466937633075,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/bend/bow (at the waist)': 0.5102316213722198,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/carry/hold (an object)': 0.6544299296389664,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/climb (e.g., a mountain)': 0.11858355788898292,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/close (e.g., a door, a box)': 0.24730749081212594,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/crouch/kneel': 0.37864294304590784,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/cut': 0.23370729929645434,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/dance': 0.6692521126811624,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/dress/put on clothing': 0.08350067878855291,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/drink': 0.378015286264672,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/drive (e.g., a car, a truck)': 0.632076390189445,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/eat': 0.4403115326469822,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/enter': 0.0489432489651446,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/fall down': 0.1958661876487952,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/fight/hit (a person)': 0.5417155907456872,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/get up': 0.40821602451137107,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/give/serve (an object) to (a person)': 0.16735980046346485,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/grab (a person)': 0.12585601545399266,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/hand clap': 0.4121450206697173,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/hand shake': 0.14808346164749678,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/hand wave': 0.1351064377829511,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/hit (an object)': 0.1565221968532169,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/hug (a person)': 0.3131640025620841,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/jump/leap': 0.19169379800173414,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/kiss (a person)': 0.4511101048191475,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/lie/sleep': 0.5070461124074798,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/lift (a person)': 0.16041297378061492,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/lift/pick up': 0.046137077364503586,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/listen (e.g., to music)': 0.05064308377278025,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/listen to (a person)': 0.6930314054518483,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/martial art': 0.4792668449573899,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/open (e.g., a window, a car door)': 0.33303843175451436,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/play musical instrument': 0.6854144356424285,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/point to (an object)': 0.008190591507090613,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/pull (an object)': 0.030260108898131854,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/push (an object)': 0.08657010175807288,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/push (another person)': 0.049630232552342675,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/put down': 0.04525505516075375,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/read': 0.46418561337472286,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/ride (e.g., a bike, a car, a horse)': 0.4866691088045868,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/run/jog': 0.609256187694392,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/sail boat': 0.2834965157071825,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/shoot': 0.4432708318403956,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/sing to (e.g., self, a person, a group)': 0.4226643026272972,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/sit': 0.8004915834582601,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/smoke': 0.3009767764066721,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/stand': 0.8444927323891764,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/swim': 0.7150849026538953,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/take (an object) from (a person)': 0.0909614218087088,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/take a photo': 0.05589583957630578,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/talk to (e.g., self, a person, a group)': 0.8221556167362185,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/text on/look at a cellphone': 0.2101792269015712,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/throw': 0.0739420237625154,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/touch (an object)': 0.3704596901246441,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/turn (e.g., a screwdriver)': 0.04368915509960961,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/walk': 0.78746549181684,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/watch (a person)': 0.7261317750622113,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/watch (e.g., TV)': 0.19887543058009893,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/work on a computer': 0.358959317415066,
  'PascalBoxes_PerformanceByCategory/AP@0.5IOU/write': 0.1895039611343681,
  'PascalBoxes_Precision/mAP@0.5IOU': 0.3489168605061007}
```
Will continue (it will take time) to other backbones.
